### ISSUE TITLE
您好，问下这个推理框架可以结合TensorRT进行使用吗？

### ISSUE THREAD

**Issue by WuShaogui** [wuba/dl_inference#6]
您好，主要担心推理速度是否达到实时，所以问问，关于结合TensorRT,您有什么思路？

**Comment by fengyu10** [comment]
可以结合TensorRT使用，月内会有更新，此次更新有TensorRT结合使用的示例。

**Comment by infichen** [comment]
dl_inference当前已经更新，集成TensorRT推理，详细可参见https://mp.weixin.qq.com/s/XQrhdD3dwY4gMMdWppHpXw

**Comment by WuShaogui** [comment]
> dl_inference当前已经更新，集成TensorRT推理，详细可参见https://mp.weixin.qq.com/s/XQrhdD3dwY4gMMdWppHpXw

谢谢回复，你们的工作很厉害，我在工作中也使用了TensorRT，由于是工业场景，所以要求速度较快，最终选择使用C++开发的DLL 接口，然后供其他语言调用
