### ISSUE TITLE
tensorrt版本

### ISSUE THREAD

**Issue by 520jefferson** [wuba/dl_inference#9]
目前支持tensorrt 8.0吗？

**Comment by binjiajia** [comment]
> 目前支持tensorrt 8.0吗？

目前只支持TensorRT 7.1.3，后续计划支持TensorRT 8.0，可以持续关注下

**Comment by 520jefferson** [comment]
> 

赞，有个大致的时间节点没？
另外，几十亿或上百亿的大模型目前支持吗？

**Comment by binjiajia** [comment]
> 

> 


> > 
> 
> 赞，有个大致的时间节点没？ 另外，几十亿或上百亿的大模型目前支持吗？

时间节点暂时还没有。我们需要积攒足够的使用经验才放心开源出来，这样才可以很好的解决大家的需求和问题。
